spring:
  application:
    name: foodsave-backend
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-only}
      expiration: 86400000 # 24 hours

# Server configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.foodsave.backend: DEBUG
    org.springframework.security: DEBUG
